### ISSUE TITLE
Issue loading contacts from OSX CardDAV Server

### ISSUE THREAD

**Issue by realriot** [blind-coder/rcmcarddav#109]
I'm running a CardDAV Server on an OS X server system. After configuring the plugin the addressbook still remains empty. After setting DEBUG I noticed that the contacts are loaded successfully

```
...
  <response>
    <href>/addressbooks/users/user%40domain.de/addressbook/42AAC558-FC78-469A-96AF-3D2E9AB4C8BC.vcf</href>
    <propstat>
      <prop>
        <getcontenttype>text/vcard;charset=utf-8</getcontenttype>
        <getetag>"aa9bfc2f77fb4a0dedaa29cc83f78e58"</getetag>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
...
```

but the last line within the debug shows me an unauthorized request:

```
</multistatus>',
)
[08-Aug-2015 20:25:49 +0200]: <7tbemd4v> BACKEND: (cdfopen) query_addressbook_multiget requesting https://my.server.de:8443/addressbooks/users/user@domain.de/addressbook/ [RL 5]
[08-Aug-2015 20:25:49 +0200]: <7tbemd4v> BACKEND: (update_addressbook) UPDATE addressbook 2
[08-Aug-2015 20:25:51 +0200]: <7tbemd4v> BACKEND: (cdfopen) Code: 401
[08-Aug-2015 20:25:51 +0200]: <7tbemd4v> BACKEND: (cdfopen) success: array (
  'status' => 401,
  'headers' =>
  Httpful\Response\Headers::__set_state(array(
     'headers' =>
    array (
      'strict-transport-security' => 'max-age=604800',
      'date' => 'Sat, 08 Aug 2015 18:25:51 GMT',
      'content-type' => 'text/html;charset=utf-8',
      'www-authenticate' => 'basic realm="home.fritz.box"',
      'server' => 'Twisted/13.2.0 TwistedWeb/9.0.0',
      'content-length' => '141',
      'dav' => '1, access-control, calendar-access, calendar-schedule, calendar-auto-schedule, calendar-availability, inbox-availability, calendar-proxy, calendarserver-private-events, calendarserver-private-comments, calendarserver-sharing, calendarserver-sharing-no-scheduling, calendar-query-extended, calendar-default-alarms, calendar-managed-attachments, calendarserver-partstat-changes, calendar-no-timezone, calendarserver-recurrence-split, addressbook, extended-mkcol, calendarserver-principal-property-search, calendarserver-principal-search, calendarserver-home-sync',
      'connection' => 'close',
    ),
  )),
  'body' => '<html><head><title>Unauthorized</title></head><body><h1>Unauthorized</h1><p>You are not authorized to access this resource.</p></body></html>',
)
```

Any hint what's going wrong here?

**Comment by blind-coder** [comment]
Are you sure that your addressbook server sends a realm of '"home.fritz.box"'?
This looks more like your router.

**Comment by realriot** [comment]
Yes it's the server. It's a hostname which is given bei the router using the "fritz.box" as domainname...

**Comment by realriot** [comment]
Do you need more informations? A better log?

**Comment by blind-coder** [comment]
Sorry, got a lot to do at the moment. I'll get back to you.

**Comment by blind-coder** [comment]
When creating an addressbook, it's normal that there is one failed login with an HTTP 401.
This is necessery to get the authentication scheme from the server (basic or digest, basic in your case).
Subsequent queries to the addressbook should work fine.

Can you access your roundcubes database and check if carddav_addressbooks is populated correctly with authentication_scheme set to "basic"?

**Comment by realriot** [comment]
Looking at the schema and comparing it with

```sqlite> select * from carddav_addressbooks;
1|CardDAV Server|%u|{DES_KEY}abc123|https://192.168.178.4:8443/addressbooks/users/%u/addressbook/|1|1|2015-08-14 05:56:01|00:00:30||unknown|Personal|0```

this sql element shows me "unknown" as identified authentication_scheme...

**Comment by blind-coder** [comment]
Huh, that's strange.
Try running this on the sqlite:
```sql
carddav_addressbooks SET schema='basic' WHERE schema='unknown';
```

**Comment by realriot** [comment]
Did it, but didn't solve the problem...

**Comment by blind-coder** [comment]
Very strange... I'm afraid I'm unable to help any more here, beause this looks very much like an authentication issue against your OSX server. I have no OSX server available for testing.

**Comment by pelletierr** [comment]
I've got the same issue and could provide an account to give you access

**Comment by pelletierr** [comment]
Wierd, it's working this morning...

**Comment by troglodyne** [comment]
I can tell you why this is happening. When the `scheme` is set to `auto` in `carddav_common.php`, the code attempts to do a request to the server which it knows will fail (in order to get the 401 challenge header to pick out the authentication method from.

Unfortunately, when it attempts the REPORT call in question, it gets 400 bad request instead from Apple's calendar server software (which does not issue the challenge header).

Response Headers:
```
HTTP/1.1 400 Bad Request
Content-Type: text/html;charset=utf-8
Strict-Transport-Security: max-age=604800
Content-Length: 128
Server: Twisted/16.6.0 TwistedWeb/9.0.0
Date: Tue, 03 Dec 2019 15:17:12 GMT
Connection: close
```
Request Headers:
<html><head><title>Bad Request</title></head><body><h1>Bad Request</h1><p>REPORT request body may not be empty</p></body></html>

The reason why it "just works" for pelletierr a morning later is due to earlier calls which failed on PROPFINDs (which actually got the auth scheme data and saved it to the addressbook properties in the database, as PROPFINDs don't issue 400s here). Unfortunately, since one typically adds the calendar and attempts synchronization in the same execution context, this data never propagates back up to the in-memory copy of the `$carddav` config passed into `cdfopen` within `carddav_common.php`. As such you have to wait until the refresh interval expires for your carddav connection for it to actually fetch the data.

Unfortunately, one cannot just work around this by simply adding the 'authentication_scheme' key to the connection that gets setup in `config.inc.php`.

I'm working on a patch for this behavior now, as I see a few things which could resolve this:
* Allow setting the authentication_scheme up front in `config.inc.php`
* Send the full request you would have normally sent when attempting to find out the scheme so as to avoid bad request errors preempting challenge header issuance.
* Ensure `$carddav` config it is re-fetched in the appropriate contexts when updated within the `cdfopen` function.

**Comment by troglodyne** [comment]
yep, just adding
```
                if (array_key_exists('content',$http_opts) && strlen($http_opts['content'])>0 && $http_opts['method'] != "GET"){
                    $httpful->body($http_opts['content']);                         
                } 
```
Like is done below to the 'real' request causes the request we expect to fail to now fail in the 'expected' manner.

**Comment by mstilkerich** [comment]
This should be fixed in v4, which uses an carddavclient lib that always sends the full request even when auth mechanism needs to be still negotiated.
