### ISSUE TITLE
DB tables don't get created, yet migrations get marked in DB as processed

### ISSUE THREAD

**Issue by Cysioland** [blind-coder/rcmcarddav#159]
PHP 7.0.8, MySQL 5.7.13, Roundcube 1.2.1.

Nothing meaningful in logs, apart from lines like `In migration: [here is migration name]` and `Found [n] matches`

**Comment by mstilkerich** [comment]
Sorry that you never got a reply. I'm closing this because you are probably not interested in this anymore after such a long time. For me, the migration works including starting from an empty database with the current v4 development branch. Thus I believe this issue might have been fixed in the meantime. If you are still having issues, please comment/reopen.
