### ISSUE TITLE
Login-hook not executed with Google 2FA

### ISSUE THREAD

**Issue by blind-coder** [blind-coder/rcmcarddav#175]
Opening a new issue to further track the discussion from #96 

> Thank you for that hint, I've investigated further by putting some log statements there and it looks like that the login-hooks are not working in case of "twofactor_gauthenticator" plugin is enabled. Temporary disabled the 2-factor auth and "checkMigrations" and "init_presets" are executed.
> 
> Now the question is why is this happen that "login_after" hooks are not executed in case of 2-factor auth is active (also registering an "login_after" hook)...perhaps a sort/sequence order issue or other hook should be used instead of "login_after".

**Comment by mstilkerich** [comment]
The twofactor_gauthenticator plugin captures the login_after hook by installing a hook that does not return, thereby preventing all remaining login_after hooks of other plugins be called.

As a workaround, you can place the twofactor_gauthenticator plugin as the very last plugin in the list of enabled plugins in the roundcube configuration. This appears to resolve the issue (see #304).

I'm closing this issue since it is not a problem of the rcmcarddav plugin.
