### ISSUE TITLE
Images assigned in plugin do not store in the CardDAV server

### ISSUE THREAD

**Issue by conspacer** [blind-coder/rcmcarddav#182]
When creating a contact in the RC interface (in the cardDAV addressbook via this plugin), all data is posted to the cardDAV server (in my case Nextcloud 11.1) and contacts are remotely created.

Images assigned in the RC interface, and showing correctly in RC, do not seam to get included in the cardDAV contact entry. Inspecting the contatcs from the Nextcloud interface show no contact images.

Reversely, contacts created in the cardDAV server (Nextcloud) with an image assigned get pushed to the RC interface (via this plugin) correctly. The contact images do show up in the RC addressbook interface.
I have tried with tiny images (50k) and larger ones (999k), both do not work RoundCube CardDAV Plugin -> CardDAV Addressbook Server.

**Comment by mstilkerich** [comment]
Hello,

sorry for the very late reply.

I tried with the current v4 development branch of RCMCardDAV and Nextcloud 18. An image I added in roundcube to a contact shows up fine in Nextcloud's contact app. So I assume this issue is resolved and will close it.

If you still happen to have this problem with the v4 branch and current nextcloud versions, please comment / reopen and I'll look into it.
