### ISSUE TITLE
Does not sync contacts

### ISSUE THREAD

**Issue by Artem2710** [blind-coder/rcmcarddav#254]
Does not sync contacts. I want to sync contacts from my Google account, settings in the attachment. The address book is created but there are no contacts in it. There are no errors in the logs. The roundcube version is 1.3.8. Tell me what could be the problem?
![2019-02-21_1100](https://user-images.githubusercontent.com/38757512/53156597-68d48400-35c8-11e9-800f-a93b9f6cb864.png)

**Comment by blind-coder** [comment]
There is a special plugin for google synchronisation, I suggest you use that.
For CardDAV access you need to change some account settings that I don't remember off-hand, otherwise you need to use OAuth authentication with the addressbook which this plugin does not and will not support just for Google.
