### ISSUE TITLE
Uncaught Error: Class 'MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger' not found

### ISSUE THREAD

**Issue by Offerel** [blind-coder/rcmcarddav#305]
After updating from the alpha branch to 4 stable, i can't load Roundcube anymore. In the logfile i see a error message:

PHP Fatal error:  Uncaught Error: Class 'MStilkerich\CardDavAddressbook4Roundcube\RoundcubeLogger' not found.

**Comment by Offerel** [comment]
Sorry, I missed that you need composer to use this version. After a php composer.phar update --no-dev, the call of Roundcube works again. Would it be possible to provide a version without composer?

**Comment by mstilkerich** [comment]
Hi,

  you need composer for installing the dependencies no matter which installation method (get rcmcarddav via composer or tarball) you choose. This was no different for alpha1.

To change this, I would have to distribute a tarball with all dependencies (and their dependencies...) included. First I would have to check the distribution conditions in the licenses of all those packages. Second chances are that these packages may include some that are also used by roundcube or other plugins, which you would then have installed likely in different versions with the potential to cause trouble.

I don't really see why you would not want to use composer and managing the dependencies centrally in roundcube (rather than having each plugin bring its dependencies with it) allows composer to detect incompatible dependency requirements and make sure you have a consistent set of plugins installed. That's why I'd rather stay with using composer.
