### ISSUE TITLE
A fixed password should only come from settings, not the database

### ISSUE THREAD

**Issue by downtownallday** [blind-coder/rcmcarddav#454]
When 'password' is fixed, the password field in the database is still preferred over the setting.

I suggest that the password should only come from the setting when it is fixed (and maybe also if hide_preferences is true).

Without this, problems can arise when there is an existing accounts table entry and the admin config is changed. Or, if the password field is encrypted (even if it's just "%p" that is encrypted) and the user subsequently changes their password, the field becomes unreadable with no way to fix it.

In the "%p" case, Utils.php returns a blank passsword instead of "%p" when the entry can't be decrypted, which breaks sync altogether.

Our specific problem (Mail-In-A-Box) has this config:

```
$prefs['_GLOBAL']['hide_preferences'] = true;
$prefs['_GLOBAL']['suppress_version_warning'] = true;
$prefs['ownCloud'] = array(
	 'name'         =>  'ownCloud',
	 'username'     =>  '%u', // login username
	 'password'     =>  '%p', // login password
	 'discovery_url' =>  null,
	 'extra_addressbooks' =>  [
		[
			'url'          =>  'https://host.tld/cloud/remote.php/dav/addressbooks/users/%u/contacts/',
			'active'       =>  true,
			'readonly'     =>  false,
			'refresh_time' => '02:00:00',
			'fixed'        =>  [ 'username','password' ],
			'preemptive_auth' => true,
			'hide'        =>  false,
		],
	],
);
```

When a user logs in, they can access their contacts. If they change their password, they can no longer access their contacts because Utils.php decrypt function is returning blank for a password instead of "%p" (because decryption fails).

If we set `$prefs['_GLOBAL']['pwstore_scheme'] = 'plain'`, then things work, but I still believe the password should only come from settings and not the database when the password is fixed.

**Comment by mstilkerich** [comment]
Hello,

  it is working as designed. The database fields are the primary source of information. Fixed fields of presets are updated during the login. It is a deliberate decision I made in v5. It simplifies the code as I can keep the admin settings limited to the frontend part of the plugin. The `name` field can take a template string which, to resolve, can require server-side requests. You don't want to do these on every roundcube request, so we need to cache it in the database. For many other fields, it would be nice to have the up to date value always used by rcmcarddav, but then I would have do differentiate between fields to take from the config file and which to take from the DB. This adds complexity to the code, and surprises for the user (some fields taken directly from preset, others not). My expectation is that preset configs are fairly stable so this tradeoff should only be a minor inconvenience.

Regarding your setup, you already named a suitable solution: Do not use the `encrypted` password scheme. It does not play well with changing the IMAP password and will always require updating the stored password. For the presets this is done automatically if the password is fixed, but only during login to roundcube (so actually for your example logout/login is the way to fix the problem). On the other hand, if the password is `%p` there is no much point in encrypting it. In case users are allowed to add custom addressbooks, you might still want encryption of their credentials. But since your have hide_preferences set to true, this is not possible. You can use the des_key scheme, which uses an roundcube installation specific key that is normally stable. Of course the admin has access to the key. However, the admin essentially will be able to get access to the user's passwords anyway if they want, so they have to be taken as a trusted party and the encryption only serves as protection in case the database contents are leaked.

A couple of unsolicited remarks regarding your config not related to the issue:
* The `suppress_version_warning` preference does not exist anymore already since v4, you can remove that setting.
* The `preemptive_auth` setting does not exist anymore. It was completely removed for some time and recently re-added because a user provided a valid use case. However, it is now called `preemptive_basic_auth`. So you can either remove it as it currently has no effect, or, if you really want to force basic authentication without being requested by the server, you should replace it by its current name.
* It appears your backend is nextcloud. Nextcloud allows to create additional addressbooks. Why do you use extra_addressbooks and only show the default addressbook in roundcube? If your users create additional addressbooks in nextcloud, they will not be visible in roundcube.
* The `hide` setting in the addressbook has no effect since you have disabled the complete settings pane by the global hide_preferences setting.

**Comment by mstilkerich** [comment]
Well fixing the non-decryptable password on login should work when the password is a fixed setting. If it doesn't work, that would be a bug.

If guess your are working on upgrading the usage of RCMCardDAV from v4 to v5 and update the config as needed? Guess is based on `https://github.com/mail-in-a-box/mailinabox/blob/main/setup/webmail.sh` which used v4.4.3.

Regarding this and the usage of multiple addressbooks the hint that in v4 discovery would always be enabled. So to translate this behavior to v5 you would set the URL as discovery_url and not use an extra_addressbook. You can shorten the discovery URL also to just point to the DAV home. Also note that `name` in v5 is used as a template for the addressbook name, whereas the account's name is now set via the `accountname` setting so you might want to adapt that as well.

So the config in the setup script referenced above would translate to (I removed defaults):

```php
$prefs['_GLOBAL']['hide_preferences'] = true;

$prefs['ownCloud'] = array(
	 'accountname'         =>  'ownCloud',
	 'username'     =>  '%u', // login username
	 'password'     =>  '%p', // login password
	 'discovery_url'          =>  'https://${PRIMARY_HOSTNAME}/cloud/remote.php/dav/',
	 'refresh_time' => '02:00:00',
	 'fixed'        =>  array('username','password'),
);
```

If you are just interested in CardDAV/CalDAV server, there are indeed simpler alternatives to Nextcloud.
* [Baïkal](https://sabre.io/baikal/): Like Nextcloud, this uses Sabre/DAV as the DAV server. Therefore it would pose the least visible change to the clients as the backend remains the same.
* [Radicale](https://radicale.org/): This one is written in Python, if that's a concern. The really nice thing about this regarding automation is that it can be configured via text configuration files including creation of users, settings passwords (via htpasswd file). It is also highly flexible regarding permissions, i.e. you can easily define public or shared calendars and addressbooks. I'm not aware that users can share calendars via the web interface though.
* [Davical](https://www.davical.org/): This one is fairly old but still maintained. Written in PHP. It is fairly powerful regarding features such as shared calendars, which could also be configured via its web interface.

I put together a comparison of the CardDAV protocol features [here](https://github.com/mstilkerich/carddavclient/blob/master/doc/QUIRKS.md) if you really want to dive into it ;-)

I don't think you will find one with built-in tools for data migrations. For addressbooks you could use https://github.com/mstilkerich/davshell (clone command), or extract the relevant code to a short PHP script. Unfortunately this does not support CalDAV. But I guess you will find a tool to do the data transfer using CalDAV protocol, without the need for a built-in tool.
